### ISSUE TITLE
Is it works?

### ISSUE THREAD

**Issue by snwefly** [bipinkrish/Mdisk-Downloader-Bot#10]
Thanks for the new update, just deployed it but i tired +10 videos so far and none of them are working, kept getting error message from the bot.

I tried few other bots from various repo and none of them worked. did these downloader bots ever  actually worked?

**Comment by bipinkrish** [comment]
What do you mean by error message? and you have to follow the usage.

**Comment by snwefly** [comment]
This error message, tired about +10 videos so far.

![image](https://user-images.githubusercontent.com/88805679/187062762-64e8b408-c772-4446-80dd-16b79cbb128f.png)


Tring to download mdisk videos so i can play it on PC.

**Comment by bipinkrish** [comment]
It explictly mentioned why it's happend, it's not number of videos its about you using links same type of videos, and btw you are getting file in your chat rigth?
