### ISSUE TITLE
/show not working 

### ISSUE THREAD

**Issue by bipinkrish** [bipinkrish/Mdisk-Downloader-Bot#14]
> S... Manual thumb always wrk fine.. Need default every time i rename that video

But /show not show the default thumb

_Originally posted by @aakash2021-cap in https://github.com/bipinkrish/Mdisk-Downloader-Bot/issues/11#issuecomment-1229518639_

**Comment by bipinkrish** [comment]
Is this happening for anyone else?

**Comment by Jasuranbot1** [comment]
/show..command not work... I'm not need show  thumb.. I have no problem for that issue... I just asking for default thumb for video

**Comment by bipinkrish** [comment]
> /show..command not work... I'm not need show thumb.. I have no problem for that issue... I just asking for default thumb for video

Is it working or not?

**Comment by bipinkrish** [comment]
@aakash2021-cap where did you hosted it?

**Comment by aakash2021-cap** [comment]
> @aakash2021-cap where did you hosted it?

Bro now working it bro before i upgrade the program ver latest so I removed the upgraded ver and it's working
