### ISSUE TITLE
Bug or not support

### ISSUE THREAD

**Issue by Jasuranbot1** [bipinkrish/Mdisk-Downloader-Bot#17]
https://mdisk.me/convertor/12x5/utEme9

File "/app/main.py", line 239, in <lambda>
    d = threading.Thread(target=lambda:down(message,link),daemon=True)
  File "/app/main.py", line 99, in down
    file,check,filename = mdisk.mdow(link,message)
TypeError: cannot unpack non-iterable NoneType object

Hang in download page

**Comment by bipinkrish** [comment]
i found out the problem will fix it

**Comment by bipinkrish** [comment]
this issue is fixed now
