### ISSUE TITLE
Request Multiple links

### ISSUE THREAD

**Issue by AsuranJ** [bipinkrish/Mdisk-Downloader-Bot#18]
Bro If u have free time plz Add batch support (multiple links)

**Comment by bipinkrish** [comment]
you can send still send links in different messeges, multiple links in one message is overhead, i would need to alter the code altogether

**Comment by AsuranJ** [comment]
Multiple links in single msg..

**Comment by bipinkrish** [comment]
It is possible but, it downloads one after the other not all at a same time

**Comment by bipinkrish** [comment]
now you cand send multiple links seperated by new lines
```
https://mdisk.me/bbbb
https://mdisk.me/aaaaa
https://mdisk.me/ccccc
```
