### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Littletonar** [bipinkrish/Mdisk-Downloader-Bot#2]
Please add heroku deploy option also.

**Comment by bipinkrish** [comment]
This repository violates Heroku's Terms and Conditions, if I add option to deploy in a single click, people will lose their accounts. However you can deploy in Heroku by selecting this repository and using Docker buildpack.

**Comment by vishansh** [comment]
How to do that ?

**Comment by bipinkrish** [comment]
> How to do that ?

You can watch some videos about it, its not that hard
