### ISSUE TITLE
Heroku crash

### ISSUE THREAD

**Issue by Jaijegas** [bipinkrish/Mdisk-Downloader-Bot#21]
![image](https://user-images.githubusercontent.com/113474934/190706776-0a17e9e4-d21d-4310-9f51-5190fc0a414f.png)
Bro how to solve this Issue

**Comment by Littletonar** [comment]
Did you get the solution?
If yes, then please tell me also..

**Comment by jagalitiger** [comment]
> Did you get the solution? If yes, then please tell me also..

change web to worker in procfile

**Comment by jagalitiger** [comment]
![Screenshot_2022-09-28-20-55-36-250_com android chrome](https://user-images.githubusercontent.com/112116859/192820460-a9cb1941-365a-4fe1-a860-a43ac8dbcb6e.jpg)

**Comment by jagalitiger** [comment]
![IMG_20220928_205921](https://user-images.githubusercontent.com/112116859/192821218-274a30de-f9b4-4d96-a29c-95a56a4c862b.jpg)
