### ISSUE TITLE
Can't remove the restriction

### ISSUE THREAD

**Issue by diethard** [bipinkrish/Mdisk-Downloader-Bot#22]
![Picsart_22-09-24_19-44-13-937](https://user-images.githubusercontent.com/37825869/192102766-a858545a-d9a2-42c0-8293-c30657a425c5.jpg)

I tried 3 different videos and i got this same error. 
It keeps saying "Can't remove the restriction, you have to use MX player to play this video. This happens because either the file length is too small or video doesn't have separate audio layer".

Please help.

**Comment by bipinkrish** [comment]
I can't remove that, it is what it is
