### ISSUE TITLE
manual run in Windows

### ISSUE THREAD

**Issue by githubprogit** [bipinkrish/Mdisk-Downloader-Bot#24]
Where add variable during locally deployment

**Comment by jagalitiger** [comment]
main.py

**Comment by bipinkrish** [comment]
added support to run this repo in windows, if you want to run manually then update the ENV in mdisk.py

**Comment by bipinkrish** [comment]
not tested but should work fine, report if any problems occured

**Comment by jagalitiger** [comment]
How to run in windows... Any demo videos?

**Comment by bipinkrish** [comment]
> How to run in windows... Any demo videos?

Just change variable "iswin" value to 1 in mdisk.py file
