### ISSUE TITLE
only showing downloading

### ISSUE THREAD

**Issue by sagar271** [bipinkrish/Mdisk-Downloader-Bot#3]
Deployed in TG. 
After passing command and link, its showing downloading message. but nothing happening
![Screenshot 2022-08-06 210457](https://user-images.githubusercontent.com/23516708/183255762-db4e78f0-0946-4f43-98e8-d3148a2bfa1c.png)

**Comment by bipinkrish** [comment]
Check if video is not deleted in Mdisk server and you just using expired link, you can also check logs where you hosted your bot to get more details

**Comment by bipinkrish** [comment]
I will try making bot more interactive and give more details of the status

**Comment by sagar271** [comment]
video is not deleted in mdisk.
its working fine in mobile.

**Comment by sagar271** [comment]
self._target(*self._args, **self._kwargs)
File "/app/main.py", line 45, in <lambda>
d = threading.Thread(target=lambda:down(message,link),daemon=True)
File "/app/main.py", line 22, in down
file = mdisk.mdow(link,message)
File "/app/mdisk.py", line 76, in mdow
subprocess.run([ytdlp, '--no-warning', '-k', '-f', vid_format, resp, '-o', input_video, '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
UnboundLocalError: local variable 'vid_format' referenced before assignment
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 917, in run
self._target(*self._args, **self._kwargs)
File "/app/main.py", line 45, in <lambda>
d = threading.Thread(target=lambda:down(message,link),daemon=True)
File "/app/main.py", line 22, in down
file = mdisk.mdow(link,message)
File "/app/mdisk.py", line 76, in mdow
subprocess.run([ytdlp, '--no-warning', '-k', '-f', vid_format, resp, '-o', input_video, '--user-agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36',
UnboundLocalError: local variable 'vid_format' referenced before assignment



this is the log available

**Comment by bipinkrish** [comment]
I hate to say this but for few videos ( 1-2 % ) server will not respond with the required metadata to continue downloading the video.

Please try for other links.

**Comment by sagar271** [comment]
ok. ill try and let you know

**Comment by bipinkrish** [comment]
If you don't mind you can share that link with me @StarHackz_bot

**Comment by sagar271** [comment]
sure. ill share

**Comment by bipinkrish** [comment]
This is what server is responding for you link.

![Screenshot from 2022-08-07 10-11-21](https://user-images.githubusercontent.com/87369440/183275590-faf6ad55-a6f6-4168-93dd-5790b315df41.png)

This is what expected.

![Screenshot from 2022-08-07 10-11-57](https://user-images.githubusercontent.com/87369440/183275621-26dca23c-339d-44b1-9335-d424eca3b3ed.png)

**Comment by sagar271** [comment]
so what to do

**Comment by sagar271** [comment]
i managed to download that video. but its only playable in mxplayer and splayer.
any way to bypass that

**Comment by bipinkrish** [comment]
That video length is too small, so there is no seperate layer for audio and video hence I can't able to remove MX plyer dependency
