### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by JAsuran** [bipinkrish/Mdisk-Downloader-Bot#31]
Bro

Check this link

https://mdisk.me/convertor/16x9/LcGDXb

No output came.. Download hanged in end

**Comment by bipinkrish** [comment]
Send me Logs

**Comment by JAsuran** [comment]
[]() 
[stydyapp-logs-1665928953868.txt](https://github.com/bipinkrish/Mdisk-Downloader-Bot/files/9794769/stydyapp-logs-1665928953868.txt)

**Comment by bipinkrish** [comment]
Restart bot and send logs

**Comment by JAsuran** [comment]
[stydyapp-logs-1665988546476.txt](https://github.com/bipinkrish/Mdisk-Downloader-Bot/files/9797522/stydyapp-logs-1665988546476.txt)

**Comment by bipinkrish** [comment]
> Restart bot and send logs

i meant send clean logs by restarting bot and use that link in bot then send the logs

**Comment by JAsuran** [comment]
> > Restart bot and send logs
> 
> i meant send clean logs by restarting bot and use that link in bot then send the logs

[stydyapp-logs-1666015768196.txt](https://github.com/bipinkrish/Mdisk-Downloader-Bot/files/9801331/stydyapp-logs-1666015768196.txt)

**Comment by bipinkrish** [comment]
> > > Restart bot and send logs
> > 
> > 
> > i meant send clean logs by restarting bot and use that link in bot then send the logs
> 
> [stydyapp-logs-1666015768196.txt](https://github.com/bipinkrish/Mdisk-Downloader-Bot/files/9801331/stydyapp-logs-1666015768196.txt)

This is because of weird name the vide has, i will small change so that it will only take normal characters into consideration

**Comment by JAsuran** [comment]
Ok

**Comment by bipinkrish** [comment]
fixed

**Comment by JAsuran** [comment]
> fixed

Working 👍
