### ISSUE TITLE
how to fix download mdisk video not normal play?

### ISSUE THREAD

**Issue by stard** [bipinkrish/Mdisk-Downloader-Bot#33]
I use yt-dlp download mdisk video, then use ffprobe get mediainfo , download video duration has only 9s(should be an ad
)
but video size actually more than 1GB. 

How did you solve this problem please？

**Comment by bipinkrish** [comment]
> I use yt-dlp download mdisk video, then use ffprobe get mediainfo , download video duration has only 9s(should be an ad ) but video size actually more than 1GB.
> 
> How did you solve this problem please？

did you used bot?

**Comment by awdealofficial** [comment]
message object has no attribute 'id' error

**Comment by bipinkrish** [comment]
> I have try some mdisk video, none of them work, is there some mdisk video work normaly?

for example?

**Comment by zj0395** [comment]
> 

I deploy the bot on RailWay. here a case: https://mdisk.me/convertor/17x30/aMImXT, it show me

Can't remove the restriction, you have to use MX player to play this video

This happens because either the file length is too small or video doesn't have separate audio layer

**Comment by zj0395** [comment]
> > I have try some mdisk video, none of them work, is there some mdisk video work normaly?
> 
> for example?

I deploy the bot on RailWay. here a case: https://mdisk.me/convertor/17x30/aMImXT, it show me

Can't remove the restriction, you have to use MX player to play this video

This happens because either the file length is too small or video doesn't have separate audio layer

**Comment by bipinkrish** [comment]
I can't find out pattern for that limitation and it can't be solved
