### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by sarwar1122** [bipinkrish/Mdisk-Downloader-Bot#4]
'chmod' is not recognized as an internal or external command,
operable program or batch file.

what is this error

**Comment by sarwar1122** [comment]
can you make it in GUI or something easier for noobs

**Comment by bipinkrish** [comment]
Are you using windows? This repository is made to work on Linux. If you want to use in Windows then go to https://github.com/death-angel-141/Mdisk-Downloader

**Comment by sarwar1122** [comment]
Thank You i will try that one but does that also remove mx player requirement?

**Comment by sarwar1122** [comment]
Can you explain what commands you use (in ffmpeg if you do) to seperate that extra stream which shows mx player requirement.

**Comment by bipinkrish** [comment]
the technique is to download video and audio/s in chunks seperately and merge both, ffmpeg is not the main reason here

**Comment by sarwar1122** [comment]
Thanks.
Death angel one is not working without MX player.

**Comment by bipinkrish** [comment]
Deploy this repository in some hosting service and use it. For easiness i even gave Deploy button for railway.app
