### ISSUE TITLE
Why Can't Deploy On Heroku 

### ISSUE THREAD

**Issue by Ashrafmdmatin41** [bipinkrish/Mdisk-Downloader-Bot#40]
When i Deploy on Heroku bot start only for 1 time at a time and in logs show like that error 60 sec ... I don't know know i deploy on heroku please help

**Comment by Jegaa1** [comment]
> When i Deploy on Heroku bot start only for 1 time at a time and in logs show like that error 60 sec ... I don't know know i deploy on heroku please help

Goto procfile change web to worker than try 2 deploy in heroku
