### ISSUE TITLE
Can you share the ffmpeg method to convert mdisk mp4 video without Python script

### ISSUE THREAD

**Issue by w3Abhishek** [bipinkrish/Mdisk-Downloader-Bot#41]
Hey,
Great work with the bot.

If possible, can you share the method to convert MP4 video downloaded from mdisk to normal video that can be played anywhere.

Like ffmpeg command or anything that doesn't require me to use the Python script.

Actually, I have a lot of mp4 files that I downloaded from mdisk and want to convert them.

Also, is there any way to support your work? BuyMeCoffee link or something.

Thanks :)

**Comment by bipinkrish** [comment]
Alredy encoded files can't be converted to able view anywhere, the idea here is downloading video in parts (which btw doesn't have encoding on it's own) and encode that small parts.
That's it also why it doesn't work for small videos.

I am not accepting any donations yet...

**Comment by w3Abhishek** [comment]
Can we use MX Player codec to convert those small videos too?

Have a look at this repository:
https://github.com/USBhost/MX_FFmpeg/releases
https://github.com/USBhost/MX_FFmpeg

**Comment by bipinkrish** [comment]
It is for adding additional codec support for the MXPlayer and i think it can't be used to decode the video.
