### ISSUE TITLE
Error R10 

### ISSUE THREAD

**Issue by shadowninja024** [bipinkrish/Mdisk-Downloader-Bot#6]
Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

Im facing this error on heroku

Deployment method - telegram bot
Directly connected my GitHub ac to heroku and deployed the repo
Have added vars perfectly as mentioned

Kindly please help me solve this error

**Comment by bipinkrish** [comment]
Use Docker buildpack to host
