### ISSUE TITLE
Upload not done

### ISSUE THREAD

**Issue by Jasuranbot1** [bipinkrish/Mdisk-Downloader-Bot#7]
bro... Mdisk file link contains "/" in caption that link not send output. Plz fix this.. And output need stream format with caption

**Comment by bipinkrish** [comment]
What do you mean link contains "/" in caption?

**Comment by AsuranJ** [comment]
https://mdisk.me/convertor/30x17/84fpTT

Try to download this video.. This caption contains slash

**Comment by bipinkrish** [comment]
Ohh the name of the file, i will give a fix soon

**Comment by AsuranJ** [comment]
🙂

**Comment by bipinkrish** [comment]
i pushed a new update which should solve this problem

**Comment by AsuranJ** [comment]
TQ... Working Fine now

1 more doubt.. How to get streamable output in this not.. Currently get output in file format
